# # Config file for automatic testing at travis-ci.org

# sudo: true

# dist: trusty

# services:
#   - docker
#   - postgresql

# env:
#   global:
#     - DOCKER_REPO_URL=quay.io
#     - DOCKER_REPO_OWNER=lookit
#     - DOCKER_REPO_NAME=lookit-api
#     - DOCKER_BRANCH=${TRAVIS_BRANCH/\//-}
#     - DOCKER_IMAGE_URL=$DOCKER_REPO_URL/$DOCKER_REPO_OWNER/$DOCKER_REPO_NAME
#     - PGPORT=5432

# cache:
#   directories:
#     - $HOME/docker

# notifications:
#   slack: lookit-mit:Sc6ZVxrtb0vIiXtft93BtXNI

# addons:
#   postgresql: "9.6"

# #before_script:
# #  - sudo service postgresql start

#   # We don't need the line to create the new database, apparently
#   #  - psql -c 'create database travis_ci_test;' -U postgres


# jobs:
#   include:
#     - stage: Build & Test
#       script:
#         - bash -c 'until pg_isready; do sleep 1; done'
#         - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#         - docker pull $DOCKER_IMAGE_URL:$TRAVIS_COMMIT || docker pull $DOCKER_IMAGE_URL:$DOCKER_BRANCH || true
#         - docker build
#             --file dev.Dockerfile
#             --cache-from $DOCKER_IMAGE_URL:$TRAVIS_COMMIT --cache-from $DOCKER_IMAGE_URL:$DOCKER_BRANCH
#             --build-arg GIT_COMMIT=$TRAVIS_COMMIT --build-arg GIT_TAG=$TRAVIS_TAG
#             --pull -t $DOCKER_IMAGE_URL:$TRAVIS_COMMIT .
#         - docker run --rm -it --network="host" $DOCKER_IMAGE_URL:$TRAVIS_COMMIT python manage.py test

language: python
python:
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "9.6"

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pre-commit run --all-files
  - poetry run ./manage.py test
